site_name: Monkeys UFG
site_url: https://mydomain.org/mysite

nav:
  - Bem vindo: 'index.md'
  - Blog:
      - 'blog/index.md'
  - Iniciando na OBI/Maratona:
      - 'start/intro.md'
      - 'start/cpp.md'
      - 'start/stl.md'
      - 'start/complexity.md'
      - 'start/practicing.md'
      - 'start/greedy.md'
      - 'start/twopointers.md'
      - 'start/prefixsum.md'
      - 'start/binarysearch.md'
      - 'start/bitmanipulation.md'
      - 'start/dp.md'
      - 'Grafos':
        - 'start/graphs/introducao.md'
        - 'Busca':
          - 'start/graphs/dfs.md'
          - 'start/graphs/bfs.md'
        - 'Caminho Minimo':
          - 'start/graphs/bellmanford.md'
          - 'start/graphs/floydwarshall.md'
          - 'start/graphs/dijkstra.md'
      - 'start/dsukruskal.md'
      - 'start/fenwick.md'
      - 'start/segtree.md'

  - Biblioteca:
    - 'Graphs':
      - 'library/graphs/bfs.md'
  - Sites:
      - 'sites/codeforces.md'
      - 'sites/atcoder.md'
      - 'sites/cses.md'
      - 'sites/usaco.md'
      - 'sites/cpalgo.md'
        
  - Membros: 'members.md'

theme:
  language: pt-BR
  name: material
  logo: assets/transparent_logo.png
  favicon: assets/favicon.ico
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/github
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.blocks.caption

repo_url: https://github.com/tiagopio/facesavio
repo_name: ufg_monkeys/monkeyslib

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tiagopio
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ufg_monkeys
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/ufg_monkeys

plugins:
  - search
  - glightbox
  - blog:
      blog_dir: blog
