site_name: Monkeys UFG
site_url: https://mydomain.org/mysite

nav:
  - Bem vindo: 'index.md'
  - Blog:
      - 'blog/index.md'
  - Iniciando na OBI/Maratona:
      - 'start/intro.md'
      - 'start/cpp.md'
      - 'start/stl.md'
      - 'start/complexity.md'
      - 'start/practicing.md'
      - 'start/greedy.md'
      - 'start/twopointers.md'
      - 'start/prefixsum.md'
      - 'start/binarysearch.md'
      - 'start/bitmanipulation.md'
      - 'Grafos: Introdução':
        - 'start/graphs-intro/introduction.md'
        - 'start/graphs-intro/classes.md'
        - 'start/graphs-intro/representation.md'
        - 'Busca':
          - 'start/graphs-intro/search/dfs.md'
          - 'start/graphs-intro/search/bfs.md'
        - 'Caminho Minimo':
          - 'start/graphs-intro/min-path/bellmanford.md'
          - 'start/graphs-intro/min-path/floydwarshall.md'
          - 'start/graphs-intro/min-path/dijkstra.md'
      - 'start/numbertheory.md'
      - 'start/geometry.md'
      - 'Programação Dinâmica':
        - 'start/dp/intro.md'
        - 'start/dp/knapsack.md'
        - 'start/dp/paths.md'
        - 'start/dp/lcs.md'
      - 'Grafos':
        - 'start/graphs-advanced/dsu.md'
      - 'start/fenwick.md'
      - 'start/segtree.md'

  - Biblioteca:
    - 'Graphs':
      - 'library/graphs/bfs.md'
  - Sites:
      - 'sites/codeforces.md'
      - 'sites/atcoder.md'
      - 'sites/cses.md'
      - 'sites/usaco.md'
      - 'sites/cpalgo.md'
        
  - Membros: 'members.md'

theme:
  language: pt-BR
  name: material
  logo: assets/transparent_logo.png
  favicon: assets/favicon.ico
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/github
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - content.code.copy
    - content.tooltips

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
repo_url: https://github.com/Monkeys-UFG/website
repo_name: Monkeys-UFG/website

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tiagopio
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ufg_monkeys
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/ufg_monkeys

plugins:
  - search
  - glightbox
  - blog:
      blog_dir: blog
      categories_allowed:
        - Contests
        - test
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/slider.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/slider.css  