authors:
  tiago:
    name: Tiago Pio
    description: Newbie
    avatar: https://avatars.githubusercontent.com/u/97364045?v=4
  danilo: 
    name: Danilo Lourenço
    description: Pupil
    avatar: https://avatars.githubusercontent.com/u/124076190?v=4