authors:
  tiago:
    name: Tiago Pio
    description: Newbie
    avatar: https://avatars.githubusercontent.com/u/97364045?v=4
  danilo: 
    name: Danilo Lourenço
    description: Specialist
    avatar: https://avatars.githubusercontent.com/u/124076190?v=4
  sabino:
    name: Felipe Sabino
    description: Master
    avatar: https://avatars.githubusercontent.com/u/133066719?v=4
  gustavo:
    name: Gustavo Leal
    description: Master
    avatar: https://avatars.githubusercontent.com/u/79591604?v=4
